/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package progetto_gdr;

/**
 *
 * @author grott
 */
public class GraficaGDR extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GraficaGDR.class.getName());
    private GestoreStoria motore;
    /**
     * Creates new form GraficaGDR
     */
    public GraficaGDR() {
         initComponents();
        motore = new GestoreStoria(); 
        aggiornaInterfaccia();        
    }
    
    private void aggiornaInterfaccia() {
        NodoScena attuale = motore.getScenaAttuale();

        txtRacconto.setText(attuale.getTestoNarrativo());

        try {
            Sfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progetto_gdr/immagini/" + attuale.getPathImmagine())));
        } catch (Exception e) {
            System.out.println("Immagine non trovata: " + attuale.getPathImmagine());
        }

        btnScelta.setVisible(false);
        btnScelta1.setVisible(false);
        btnScelta2.setVisible(false);

        var opzioni = attuale.getOpzioni();
        if (opzioni.size() > 0) {
            btnScelta.setText(opzioni.get(0).testo);
            btnScelta.setVisible(true);
        }
        if (opzioni.size() > 1) {
            btnScelta1.setText(opzioni.get(1).testo);
            btnScelta1.setVisible(true);
        }
        if (opzioni.size() > 2) {
            btnScelta2.setText(opzioni.get(2).testo);
            btnScelta2.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalvataggio = new javax.swing.JButton();
        btnScelta2 = new javax.swing.JButton();
        btnScelta = new javax.swing.JButton();
        btnScelta1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRacconto = new javax.swing.JTextArea();
        personaggio1 = new javax.swing.JLabel();
        personaggio2 = new javax.swing.JLabel();
        personaggio3 = new javax.swing.JLabel();
        Sfondo = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnSalvataggio.setText("Button4");
        btnSalvataggio.addActionListener(this::btnSalvataggioActionPerformed);
        getContentPane().add(btnSalvataggio);
        btnSalvataggio.setBounds(330, 10, 72, 23);

        btnScelta2.setText("jButton3");
        btnScelta2.addActionListener(this::btnScelta2ActionPerformed);
        getContentPane().add(btnScelta2);
        btnScelta2.setBounds(290, 260, 75, 23);

        btnScelta.setText("jButton1");
        btnScelta.addActionListener(this::btnSceltaActionPerformed);
        getContentPane().add(btnScelta);
        btnScelta.setBounds(10, 260, 75, 23);

        btnScelta1.setText("jButton2");
        btnScelta1.addActionListener(this::btnScelta1ActionPerformed);
        getContentPane().add(btnScelta1);
        btnScelta1.setBounds(150, 260, 75, 23);

        txtRacconto.setColumns(20);
        txtRacconto.setLineWrap(true);
        txtRacconto.setRows(5);
        jScrollPane1.setViewportView(txtRacconto);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 190, 400, 50);

        personaggio1.setText("jLabel2");
        getContentPane().add(personaggio1);
        personaggio1.setBounds(40, 140, 37, 16);

        personaggio2.setText("jLabel3");
        getContentPane().add(personaggio2);
        personaggio2.setBounds(170, 140, 37, 16);

        personaggio3.setText("jLabel4");
        getContentPane().add(personaggio3);
        personaggio3.setBounds(310, 140, 37, 16);

        Sfondo.setText("jLabel2");
        getContentPane().add(Sfondo);
        Sfondo.setBounds(0, 0, 420, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSceltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSceltaActionPerformed
        int destinazione = motore.getScenaAttuale().getOpzioni().get(0).idDestinazione;
        motore.vaiAllaScena(destinazione);
        aggiornaInterfaccia();
    }//GEN-LAST:event_btnSceltaActionPerformed

    private void btnScelta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScelta1ActionPerformed
        int destinazione = motore.getScenaAttuale().getOpzioni().get(1).idDestinazione;
        motore.vaiAllaScena(destinazione);
        aggiornaInterfaccia();
    }//GEN-LAST:event_btnScelta1ActionPerformed

    private void btnScelta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScelta2ActionPerformed
        int destinazione = motore.getScenaAttuale().getOpzioni().get(2).idDestinazione;
        motore.vaiAllaScena(destinazione);
        aggiornaInterfaccia();
    }//GEN-LAST:event_btnScelta2ActionPerformed

    private void btnSalvataggioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvataggioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvataggioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GraficaGDR().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Sfondo;
    private javax.swing.JButton btnSalvataggio;
    private javax.swing.JButton btnScelta;
    private javax.swing.JButton btnScelta1;
    private javax.swing.JButton btnScelta2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel personaggio1;
    private javax.swing.JLabel personaggio2;
    private javax.swing.JLabel personaggio3;
    private javax.swing.JTextArea txtRacconto;
    // End of variables declaration//GEN-END:variables
}
