/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package progetto_gdr;

/**
 *
 * @author grottelli.gabriele
 */
public class schermataStart extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(schermataStart.class.getName());

    /**
     * Creates new form schermataStart
     */
    public schermataStart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIstruzioni = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        SfondoStart = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnIstruzioni.setText("jButton1");
        btnIstruzioni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIstruzioniActionPerformed(evt);
            }
        });
        getContentPane().add(btnIstruzioni);
        btnIstruzioni.setBounds(317, 28, 75, 23);

        btnStart.setText("jButton1");
        getContentPane().add(btnStart);
        btnStart.setBounds(106, 230, 176, 51);

        SfondoStart.setText("jLabel1");
        getContentPane().add(SfondoStart);
        SfondoStart.setBounds(0, -4, 410, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIstruzioniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIstruzioniActionPerformed
        String messaggio = "BENVENUTO, VIANDANTE DEL DESTINO\n\n"
            + "Il mondo che stai per calcare non risponde alla forza bruta, \n"
            + "ma all'eco delle tue scelte.\n\n"
            + "📖 ASCOLTA LE OMBRE\n"
            + "Ogni luogo ha una storia. Leggi attentamente i racconti: \n"
            + "tra le righe si nascondono indizi per la tua sopravvivenza.\n\n"
            + "⚖️ IL PESO DELL'ANIMA (KARMA)\n"
            + "Qui non troverai spade o archi. La tua unica arma è la parola.\n"
            + "Ogni tua azione muterà il tuo Karma: sarai un faro di speranza \n"
            + "o un'ombra nel buio? Ricorda: il mondo cambierà con te.\n\n"
            + "🌀 TRAME DIVERGENTI\n"
            + "Non esiste un unico sentiero. Le tue decisioni plasmeranno \n"
            + "nuove scene e apriranno varchi verso finali che solo tu \n"
            + "potrai scoprire... o causare.\n\n"
            + "🕯️ MEMORIA ETERNA\n"
            + "Se senti che il destino ti sta sfuggendo di mano, usa il potere\n"
            + "del Salvataggio. Il file '.ser' custodirà la tua essenza \n"
            + "permettendoti di sfidare il tempo stesso.\n\n"
            + "Che la tua storia valga la pena di essere raccontata.";

javax.swing.JOptionPane.showMessageDialog(this, messaggio, "Cronache del Destino", javax.swing.JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnIstruzioniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new schermataStart().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SfondoStart;
    private javax.swing.JButton btnIstruzioni;
    private javax.swing.JButton btnStart;
    // End of variables declaration//GEN-END:variables
}
